// The app-owned Tauri command names, in one place.
//
// Two consumers that must agree: `build.rs` declares them to the Tauri manifest
// (which is what makes `allow-<command>` permissions exist at all), and the
// crate's tests check the capability files and the generated bindings against
// the same list. Keeping one list is what lets those checks be meaningful
// rather than comparing a hand-copy to itself.
//
// `build.rs` pulls this in with `include!`, so it cannot drift from the crate.

pub const COMMANDS: &[&str] = &[
    "launch_application",
    "write_text",
    "simulate_enter_keystroke",
    "simulate_copy_keystroke",
    "simulate_backspaces",
    "enumerate_recording_devices",
    "start_recording",
    "stop_recording",
    "cancel_recording",
    "current_recording",
    "encode_recording_for_upload",
    "transcribe_recording",
    "prewarm_model",
    "open_accessibility_settings",
    "request_accessibility_permission",
    "get_microphone_permission",
    "request_microphone_permission",
    "get_active_model",
    "get_local_transcription_readiness",
    "open_home",
    "set_active_model",
    "get_unload_policy",
    "set_unload_policy",
    "list_models",
    "download_model",
    "delete_model",
    "cancel_download",
    "pause_playback",
    "resume_playback",
    "set_auto_paste_enabled",
    "get_dictation_capability",
    "get_foreground_context",
    // Registered in the specta builder and granted by the Dictation capability,
    // but historically missing from this list, so the manifest never declared the
    // permissions those grants name. The committed autogenerated permission files
    // kept it working; a clean regeneration would not have.
    "replace_global_shortcuts",
    "is_autostart_enabled",
    "set_autostart_enabled",
];
