// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
	/**
	 *  Delivers text to the cursor, falling back to the clipboard when it cannot.
	 *
	 *  With `keep_on_clipboard`, the transcript is the intended final clipboard
	 *  state. Otherwise this command borrows the clipboard, pastes, and schedules
	 *  the previous contents to go back: the exact previous macOS pasteboard, or
	 *  the previous text on other platforms, clearing instead when there was no
	 *  previous text, so the borrowed transcript never lingers.
	 *
	 *  That restore is deferred past this command's return and is conditional. It
	 *  does not fire when a later dictation has taken the borrow over (that one
	 *  hands the same content back instead), nor when the clipboard has visibly
	 *  changed hands while borrowed, where stamping a stale snapshot over newer
	 *  content is the worse loss. A path that means to leave the transcript on the
	 *  clipboard, the reach fallback and `keep_on_clipboard`, ends the borrow
	 *  without a restore at all.
	 */
	writeText: (text: string, keepOnClipboard: boolean) =>
		typedError<WriteTextOutcome, string>(
			__TAURI_INVOKE('write_text', { text, keepOnClipboard }),
		),
	/**  Simulates pressing the Enter/Return key. */
	simulateEnterKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_enter_keystroke')),
	/**
	 *  Simulates the platform copy shortcut with layout-independent key codes.
	 *
	 *  Refuses on Windows when injected input cannot reach the foreground window,
	 *  the same gate `write_text` applies to the paste. The copy needs it more.
	 *  A dropped paste loses a transcript that is still on the clipboard, while a
	 *  dropped copy produces a plausible wrong answer: `captureSelection` posts the
	 *  copy, waits, then reads the clipboard, so a copy UIPI swallowed hands back
	 *  whatever the user already had there as if they had selected it, and that
	 *  text goes on to a transformation provider. Enter and Backspace need no such
	 *  gate: Enter follows a paste already proved reachable, and backspaces that go
	 *  nowhere leave the text visibly undeleted rather than answering wrongly.
	 */
	simulateCopyKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_copy_keystroke')),
	/**
	 *  Simulates pressing Backspace `count` times.
	 *
	 *  One press deletes one grapheme cluster, so the caller counts graphemes, not
	 *  UTF-16 code units. Refuses above the cap rather than deleting part of it.
	 */
	simulateBackspaces: (count: number) =>
		typedError<null, string>(__TAURI_INVOKE('simulate_backspaces', { count })),
	enumerateRecordingDevices: () =>
		typedError<string[], RecorderError>(
			__TAURI_INVOKE('enumerate_recording_devices'),
		),
	/**
	 *  Start recording, returning the blob id the recording will be published
	 *  under and the microphone it opened.
	 *
	 *  The id exists before its blob does: `stop` publishes the blob under it and
	 *  `cancel` burns it with no blob ever written. The host mints it so ownership
	 *  is decided here rather than asserted by a caller.
	 *
	 *  `device_identifier` is optional; `None` records from the system default, and
	 *  a name that is no longer present falls back to the default rather than
	 *  failing. Either way `device` reports what actually opened, so the caller
	 *  never has to enumerate devices just to discover what it got. Fails with
	 *  `Busy` when another window is already recording.
	 */
	startRecording: (deviceIdentifier: string | null) =>
		typedError<HostRecording, RecorderError>(
			__TAURI_INVOKE('start_recording', { deviceIdentifier }),
		),
	/**
	 *  Stop the recording named by `audio_blob_id`, publish its blob, and report
	 *  the committed audio.
	 *
	 *  Restricted to the window that started it: only the owner can turn its
	 *  recording into bytes it can then read. A caller that names a recording which
	 *  has already ended, is not the live one, or belongs to another window gets
	 *  `NotRecording`, which makes an idempotent stop (push-to-talk releasing after
	 *  its recording was already supplanted) a clean typed no-op.
	 */
	stopRecording: (audioBlobId: string) =>
		typedError<StoppedRecording, RecorderError>(
			__TAURI_INVOKE('stop_recording', { audioBlobId }),
		),
	/**
	 *  Cancel the recording named by `audio_blob_id`, discarding its audio.
	 *
	 *  Owner-only, and it produces nothing: the minted blob id is burnt and no blob
	 *  is ever written under it. The host cancels by another route entirely (the
	 *  owner window being destroyed, wired in `lib.rs`), which needs no command and
	 *  therefore no grant.
	 */
	cancelRecording: (audioBlobId: string) =>
		typedError<null, RecorderError>(
			__TAURI_INVOKE('cancel_recording', { audioBlobId }),
		),
	/**
	 *  The recording this window owns, or `null`.
	 *
	 *  Reload does not destroy a window, so a window that reloads mid-recording
	 *  still owns that recording and would otherwise have no way to name it. This
	 *  is the only reason the single recorder cannot wedge until the owner window
	 *  is destroyed.
	 *
	 *  A pure read, and the same shape `start` returns, so a recovered recording is
	 *  not a different kind of thing from a freshly started one: the caller learns
	 *  which microphone it opened without having been the one that opened it, and
	 *  learns from `endedReason` whether that microphone is still running. A
	 *  recording whose capture died while the JS was gone is found here and stopped
	 *  like any other, which publishes what it captured.
	 */
	currentRecording: () =>
		typedError<
			{
				audioBlobId: string;
				device: DeviceAcquisition;
				/**
				 *  `None` while capture is running. `Some` means capture is over and this
				 *  recording is waiting to be stopped (publishing what it captured) or
				 *  cancelled (discarding it).
				 */
				endedReason: EndedReason | null;
			} | null,
			RecorderError
		>(__TAURI_INVOKE('current_recording')),
	/**
	 *  Canonical transcribe-by-id path. Resolves the canonical local blob, decodes
	 *  it, then runs inference on the **active** model with the caller's advisory
	 *  hints. The caller names audio and hints; it does not name a model.
	 */
	transcribeRecording: (audioBlobId: string, hints: TranscriptionHints) =>
		typedError<TranscriptionOutcome, TranscriptionError>(
			__TAURI_INVOKE('transcribe_recording', { audioBlobId, hints }),
		),
	/**
	 *  Prewarm the active local model so a following transcribe finds it warm. The
	 *  frontend fires this fire-and-forget at capture start (manual record or VAD
	 *  listen) for a local route, overlapping the ~1 s model load with the user's
	 *  speech instead of paying it after they stop.
	 *
	 *  Idempotent and cheap: a no-op when the active model is already resident.
	 *  Shares the one load path with `transcribe_recording` (`ModelCache::prewarm`
	 *  and `transcribe` both resolve through `ensure_loaded`), so the model warmed
	 *  here is exactly the one transcribe will use, because there is only one. A
	 *  failure here is non-fatal: transcribe will load normally and surface any real
	 *  error then.
	 */
	prewarmModel: () =>
		typedError<null, TranscriptionError>(__TAURI_INVOKE('prewarm_model')),
	/**
	 *  Open macOS Accessibility settings.
	 *
	 *  This is intentionally a fixed command instead of a general command
	 *  runner. The app only needs this one OS handoff, so the frontend should
	 *  not receive shell or process execution privileges.
	 */
	openAccessibilitySettings: () =>
		typedError<null, string>(__TAURI_INVOKE('open_accessibility_settings')),
	/**
	 *  Show the macOS Accessibility permission prompt.
	 *
	 *  macOS never lets an app grant itself Accessibility, so this only surfaces the
	 *  system prompt (which also adds the app to the Accessibility list, toggled
	 *  off); the live grant is observed by the Rust tap supervisor, not returned
	 *  here. Off macOS there is no such prompt, so this does nothing. Pairs with
	 *  `open_accessibility_settings` the way `request_microphone_permission` does
	 *  with the microphone privacy page.
	 */
	requestAccessibilityPermission: () =>
		__TAURI_INVOKE<void>('request_accessibility_permission'),
	/**
	 *  Read the microphone authorization the OS records up front.
	 *
	 *  One owner for every platform. macOS reads AVFoundation's
	 *  `authorizationStatusForMediaType:` directly, so all four Apple states arrive
	 *  intact and a not-yet-asked user is reported as `NotDetermined` instead of
	 *  being flattened into a denial. Windows reads the CapabilityAccessManager
	 *  ConsentStore. Every other platform (Linux) returns `Unknown`, where there is
	 *  no such store and the stream-open fallback stays the sole classifier.
	 */
	getMicrophonePermission: () =>
		__TAURI_INVOKE<MicrophonePermission>('get_microphone_permission'),
	/**
	 *  Elicit a microphone grant the way each platform allows, and answer with the
	 *  authorization that holds once there is nothing left to elicit.
	 *
	 *  Returning the status is what lets the caller ask once. macOS is the only
	 *  platform that can move the answer inside this call: when the status is
	 *  `NotDetermined` it raises the system prompt and awaits the real completion
	 *  handler, so the returned value is the user's decision, not a guess. Every
	 *  other status is already final, so prompting is a documented no-op and the
	 *  call short-circuits.
	 *
	 *  Windows has no programmatic grant for an unpackaged desktop app, so a
	 *  `Denied` consent store deep-links the privacy page and reports `Denied`: the
	 *  toggle happens in Settings, outside this call. Other platforms (Linux) have
	 *  no such affordance and report `Unknown`.
	 */
	requestMicrophonePermission: () =>
		typedError<MicrophonePermission, string>(
			__TAURI_INVOKE('request_microphone_permission'),
		),
	/**
	 *  The active local model's identity and whether it can run right now, or
	 *  `None` when nobody has chosen one.
	 *
	 *  **Administration only.** Home holds this grant because Home chooses the
	 *  active model and must show which one that is. Applications are not granted
	 *  it and read `get_local_transcription_readiness` instead, which answers the
	 *  question they actually have without handing them an identity they could
	 *  start keying behaviour off.
	 */
	getActiveModel: () =>
		__TAURI_INVOKE<{
			id: string;
			/**
			 *  The curated display name, so a caller can name the model in an error
			 *  without holding a catalog of its own.
			 */
			name: string;
			/**
			 *  Whether the model's file is present on this machine. Disk presence, the
			 *  same verdict `list_models` renders; never a statement about memory.
			 */
			installed: boolean;
			/**
			 *  Whether this model accepts an initial prompt, so a caller knows whether
			 *  to offer the field at all. The runtime still guards the real decision at
			 *  use and reports what it applied, so a stale hint can only hide a field,
			 *  never misfeed the model.
			 */
			supportsPrompt: boolean;
			/**  Whether this model takes a spoken-language hint. */
			supportsLanguage: boolean;
		} | null>('get_active_model'),
	/**
	 *  Make `model_id` the active local model, or clear the choice with `null`.
	 *  Home's administration write: the only way the active model changes.
	 */
	setActiveModel: (modelId: string | null) =>
		typedError<null, SettingsError>(
			__TAURI_INVOKE('set_active_model', { modelId }),
		),
	/**
	 *  Whether the local transcription route can run right now, and what it accepts.
	 *
	 *  The one ordinary application-facing read. It exists so an app can warn the
	 *  user *before* they speak, which matters because the surface that reports a
	 *  failure afterwards (a dictation pill) has nowhere to put a recovery action.
	 *  Advisory only: it never mutates, and it is not a gate the caller must pass
	 *  before transcribing.
	 */
	getLocalTranscriptionReadiness: () =>
		__TAURI_INVOKE<LocalTranscriptionReadiness>(
			'get_local_transcription_readiness',
		),
	/**
	 *  Take the user to the app that can fix an unavailable local transcription
	 *  route.
	 *
	 *  The app shell owns this navigation. The host reports that the route is
	 *  unavailable, an application decides how to present it, and getting the user
	 *  to Home is neither of their jobs: an application asks the shell to open
	 *  Home, and the shell does. Home is the model administration window and
	 *  nothing else now (ADR-0180), so there is no section to name: opening the
	 *  window is the whole act.
	 *
	 *  It mutates no transcription state: it opens a window, and the user chooses.
	 */
	openHome: () => __TAURI_INVOKE<void>('open_home'),
	/**  When the host drops the resident model. */
	getUnloadPolicy: () => __TAURI_INVOKE<UnloadPolicy>('get_unload_policy'),
	/**
	 *  Set the unload policy. Host-owned and durable alongside the active model:
	 *  Rust owns the idle clock because a backgrounded webview timer throttles
	 *  exactly when idle eviction must fire (ADR-0012), and now owns the value too,
	 *  so it applies from launch instead of waiting for a webview to reconcile it.
	 *  It carries no model identity, so it applies whether or not a model is active.
	 */
	setUnloadPolicy: (policy: UnloadPolicy) =>
		typedError<null, SettingsError>(
			__TAURI_INVOKE('set_unload_policy', { policy }),
		),
	/**
	 *  The full local GGUF catalog with per-model download status. The picker's one
	 *  data source: which models exist, what they can do, and which are on disk.
	 */
	listModels: () => __TAURI_INVOKE<ModelInfo[]>('list_models'),
	/**
	 *  Download a catalog model into the shared Hugging Face cache, reporting
	 *  cumulative progress on `on_progress`. Registered under `download_id` so
	 *  `cancel_download(download_id)` can abort the in-flight transfer (the aborted
	 *  task drops mid-download; hf-hub leaves a temp file, never a corrupt final).
	 *  A no-op-fast when the file is already cached (hf-hub reuses it).
	 */
	downloadModel: (
		modelId: string,
		downloadId: string,
		onProgress: Channel<DownloadProgress>,
	) =>
		typedError<null, CatalogError>(
			__TAURI_INVOKE('download_model', { modelId, downloadId, onProgress }),
		),
	/**
	 *  Remove a downloaded model's file from the shared HF cache, reclaiming its
	 *  space, and stand down the active choice if this was it.
	 *
	 *  One host operation, not two invokes, because the host owns both halves: the
	 *  file and the active-model setting live on the same side of the boundary, and
	 *  splitting them would let a caller succeed at deleting and then fail (or
	 *  forget) to clear, leaving an active model that cannot run and a UI that never
	 *  learned. Clearing is deliberate rather than promoting another installed
	 *  model: there is no substitution, so the next transcription fails with an
	 *  actionable error until the user chooses again.
	 *
	 *  Best-effort on the file: removes the snapshot pointer and its backing blob. A
	 *  no-op when the model is not downloaded. Other quantizations in the same repo
	 *  are untouched (each is its own blob + pointer).
	 */
	deleteModel: (modelId: string) =>
		typedError<null, CatalogError>(__TAURI_INVOKE('delete_model', { modelId })),
	/**
	 *  Abort the in-flight download registered under `download_id`, if any. The
	 *  matching `download_model` call then resolves with an `Err` (and the dropped
	 *  task leaves a temp file in the HF cache, never a corrupt final). A no-op when
	 *  nothing is downloading under that id, so it is always safe to call.
	 */
	cancelDownload: (downloadId: string) =>
		__TAURI_INVOKE<void>('cancel_download', { downloadId }),
	/**
	 *  Pause every system media session currently playing. Returns one opaque token
	 *  per session paused, to hand back to `resume_playback`. Pausing is gated to
	 *  never *start* playback: only sessions observed playing are touched, and the
	 *  dedicated pause command (never a play/pause toggle) is sent.
	 */
	pausePlayback: () => __TAURI_INVOKE<string[]>('pause_playback'),
	/**
	 *  Resume the sessions named by `sessions`, which must be tokens returned by a
	 *  prior `pause_playback`. A session that vanished, was already resumed by the
	 *  user, or can't be resumed is silently skipped. Safety rule: we only ever send
	 *  *play* to a session we personally paused.
	 */
	resumePlayback: (sessions: string[]) =>
		__TAURI_INVOKE<void>('resume_playback', { sessions }),
	/**
	 *  Tell the keyboard supervisor whether auto-paste-at-cursor is enabled. Paste
	 *  writes a synthetic Cmd/Ctrl+V through the macOS Accessibility grant the tap
	 *  watches, so the supervisor holds the tap whenever paste is on to track that
	 *  grant (and surface the notice when it is missing or stale). It is the only
	 *  reason to hold the tap (ADR-0117). The FE pushes this on startup and whenever
	 *  the output settings change. A no-op off macOS, where paste needs no grant.
	 */
	setAutoPasteEnabled: (enabled: boolean) =>
		__TAURI_INVOKE<void>('set_auto_paste_enabled', { enabled }),
	/**
	 *  The current paste-at-cursor capability: whether a synthetic Cmd/Ctrl+V can
	 *  land (on macOS, whether the Accessibility grant is live and the tap is
	 *  healthy). The FE seeds from this on attach, then tracks
	 *  `DictationCapabilityEvent` for changes; it never probes the OS itself. The
	 *  Rust supervisor owns the value and the tap's lifecycle, so there is no `start`
	 *  command for the FE to call.
	 */
	getDictationCapability: () =>
		__TAURI_INVOKE<DictationCapability>('get_dictation_capability'),
	/**
	 *  Reports the foreground application and focused-field kind.
	 *
	 *  Never errors: every platform refusal degrades to `None` / `Unknown` so a
	 *  probe failure can never fail a dictation.
	 */
	getForegroundContext: () =>
		__TAURI_INVOKE<ForegroundContext>('get_foreground_context'),
	replaceGlobalShortcuts: (registrations: GlobalShortcutRegistration[]) =>
		typedError<null, string>(
			__TAURI_INVOKE('replace_global_shortcuts', { registrations }),
		),
	isAutostartEnabled: () =>
		typedError<boolean, string>(__TAURI_INVOKE('is_autostart_enabled')),
	setAutostartEnabled: (enabled: boolean) =>
		typedError<null, string>(
			__TAURI_INVOKE('set_autostart_enabled', { enabled }),
		),
};

/** Events */
export const events = {
	dictationCapabilityEvent: makeEvent<DictationCapabilityEvent>(
		'dictation-capability-event',
	),
	globalShortcutTriggered: makeEvent<GlobalShortcutTriggered>(
		'global-shortcut-triggered',
	),
	recordingEndedEvent: makeEvent<RecordingEndedEvent>('recording-ended-event'),
};

/* Types */
/**
 *  The one active local model as **Home** sees it: its exact identity and
 *  whether its file is on this machine right now.
 *
 *  Administration data, not application data (ADR-0180). Home chooses the active
 *  model, so Home is told which one it is; an ordinary application never learns
 *  model identity and reads `get_local_transcription_readiness` instead. Nothing
 *  here reports residency: `installed` is disk presence, and how many models are
 *  resident or warm stays host-private.
 */
export type ActiveModel = {
	id: string;
	/**
	 *  The curated display name, so a caller can name the model in an error
	 *  without holding a catalog of its own.
	 */
	name: string;
	/**
	 *  Whether the model's file is present on this machine. Disk presence, the
	 *  same verdict `list_models` renders; never a statement about memory.
	 */
	installed: boolean;
	/**
	 *  Whether this model accepts an initial prompt, so a caller knows whether
	 *  to offer the field at all. The runtime still guards the real decision at
	 *  use and reports what it applied, so a stale hint can only hide a field,
	 *  never misfeed the model.
	 */
	supportsPrompt: boolean;
	/**  Whether this model takes a spoken-language hint. */
	supportsLanguage: boolean;
};

/**
 *  Which advisory hints the run actually applied.
 *
 *  Built from the exact values handed to the runtime, never from what the caller
 *  asked for. A hint the active model cannot take is reported as not applied
 *  rather than dropped in silence, so a caller can tell its user that the prompt
 *  or language did not reach the recognizer instead of wondering why it had no
 *  effect.
 */
export type AppliedHints = {
	/**
	 *  The language hint the runtime received. `None` means it autodetected:
	 *  the caller asked for autodetect, sent nothing, or asked for a language
	 *  the active model does not take.
	 */
	language: string | null;
	/**
	 *  Whether the caller's initial prompt reached the runtime. `false` when the
	 *  caller sent none, or the active model does not accept one (Whisper does;
	 *  the Parakeet family does not).
	 */
	initialPrompt: boolean;
};

export type CatalogError =
	| { name: 'UnknownModel'; message: string }
	| { name: 'DownloadFailed'; message: string }
	| { name: 'DeleteFailed'; message: string };

/**
 *  Which microphone a recording actually opened, and whether that was the one
 *  asked for.
 *
 *  Serialized to match `DeviceAcquisitionOutcome` in `@epicenter/recorder`,
 *  which the browser recorder already produces, so both platforms report device
 *  acquisition in one shape.
 */
export type DeviceAcquisition =
	/**  The requested device was found and opened. */
	| { outcome: 'success'; deviceId: string }
	/**
	 *  A different device was opened. `device_id` is what actually recorded, so
	 *  an application can say which microphone it is using and persist it.
	 */
	| { outcome: 'fallback'; reason: FallbackReason; deviceId: string };

/**
 *  The single source of truth for whether Epicenter can paste a transcript at
 *  the cursor: a synthetic Cmd/Ctrl+V that, on macOS, needs the Accessibility
 *  grant. macOS is the only platform that gates it, and the only process that
 *  can authoritatively know is the one holding the tap (this one), so Rust owns
 *  this value and the frontend is a pure view over it (ADR-0117).
 *
 *  It folds two facts the frontend used to infer separately: the macOS trust
 *  probe (`AXIsProcessTrusted`) and the tap's liveness. Crucially `Broken` is
 *  distinguishable from `Active` only here, because `AXIsProcessTrusted` reports
 *  a stale post-update grant as trusted: the tap dying under a held grant is the
 *  only signal that tells them apart.
 */
export type DictationCapability =
	/**
	 *  The supervisor has not determined the value yet. Rust resolves this
	 *  synchronously at startup, so it exists only as the frontend's pre-seed
	 *  initial value before the first probe lands.
	 */
	| 'unknown'
	/**
	 *  Auto-paste-at-cursor is off, so nothing needs the grant: the tap is
	 *  deliberately not running and no Accessibility is touched. Global shortcuts
	 *  are plugin chords and work regardless.
	 */
	| 'inactive'
	/**
	 *  macOS Accessibility is not granted, so paste at cursor falls back to the
	 *  clipboard. Turning Epicenter on in System Settings unlocks the paste.
	 */
	| 'untrusted'
	/**  The tap is running and the app is trusted: paste at cursor can land. */
	| 'active'
	/**
	 *  macOS reports the app trusted, but the tap keeps dying under the held
	 *  grant: a stale post-update signature. Removing and re-adding Epicenter
	 *  in Accessibility is the fix, which `Untrusted`'s "just toggle on" is not.
	 */
	| 'broken';

/**
 *  Pushed whenever the dictation capability changes. The frontend seeds from
 *  `get_dictation_capability` on attach, then tracks this event for transitions;
 *  it never probes the OS itself. A `tauri_specta::Event`, emitted with
 *  `emit_to(app, MAIN_WINDOW)` (the Whispering webview, not the overlay) and listened
 *  through the generated `events.dictationCapabilityEvent`.
 */
export type DictationCapabilityEvent = {
	capability: DictationCapability;
};

/**
 *  Cumulative download progress for one model: bytes received so far across all
 *  of its files, and the grand total to expect. The frontend turns it into a
 *  0-100 percent.
 */
export type DownloadProgress = {
	/**
	 *  Bytes received so far. `f64` because specta forbids exporting 64-bit
	 *  ints to TypeScript; model sizes are far below `f64`'s 2^53 exact-integer
	 *  ceiling, so no precision is lost.
	 */
	bytesReceived: number | null;
	/**  Grand total bytes for the whole model (sum of the catalog file sizes). */
	totalBytes: number | null;
};

/**
 *  Why the host ended a recording's capture on its own.
 *
 *  This never describes a stop, a cancel, or an owner window being destroyed.
 *  Those are endings someone asked for, and the caller already knows about them
 *  from its own call returning.
 */
export type EndedReason =
	/**
	 *  The microphone went away while recording (`ErrorKind::DeviceNotAvailable`).
	 *  The recovery is physical: reconnect it, or pick another input.
	 */
	| 'deviceDisconnected'
	/**
	 *  The OS withdrew microphone access mid-recording
	 *  (`ErrorKind::PermissionDenied`). The device is still there and still
	 *  works; the recovery is a permission toggle, which is why this is not
	 *  folded into `DeviceDisconnected`.
	 */
	| 'permissionRevoked'
	/**
	 *  The capture stream failed for a reason the host cannot make actionable:
	 *  the configuration was invalidated, the audio host vanished, a resource
	 *  limit was hit, or the backend reported something cpal could not classify.
	 *  One variant rather than five, because the person does the same thing
	 *  about all of them.
	 */
	| 'streamFailed'
	/**
	 *  The staged file could not be written any further: the disk filled, its
	 *  volume went away, or the recording reached the longest audio a WAV can
	 *  describe (about 12 hours of mono capture).
	 *
	 *  Kept apart from `StreamFailed` because the microphone is fine and the
	 *  remedy is on the machine, not the hardware. The three storage causes are
	 *  *not* kept apart from each other: whichever one it was, the recording is
	 *  capped at what already reached disk and the next step is the same, so a
	 *  finer split would be a decorative name on a message string.
	 */
	| 'storageFailed';

export type FallbackReason =
	/**  No device was requested, so the system default was used. */
	| 'no-device-selected'
	/**  The requested device is not present, so the system default was used. */
	| 'preferred-device-unavailable';

/**  What the focused UI element revealed about itself. */
export type FocusedFieldKind =
	/**  The platform affirmatively reported a password/secure field. */
	| 'secure'
	/**  The platform affirmatively reported a non-secure element. */
	| 'notSecure'
	/**  The platform could not say. Callers treat this as not secure. */
	| 'unknown';

/**  A snapshot of what is in front of the user right now. */
export type ForegroundContext = {
	/**
	 *  Stable per-platform identity: lowercased exe file name on Windows
	 *  ("code.exe"), bundle identifier on macOS ("com.microsoft.VSCode").
	 *  `None` when the OS refuses to say (no frontmost app, or a SYSTEM-owned,
	 *  protected, or other-user process).
	 */
	appId: string | null;
	/**  Human-readable name for settings helper UI only. Never matched against. */
	appName: string | null;
	focusedField: FocusedFieldKind;
};

export type GlobalShortcutRegistration = {
	commandId: string;
	accelerator: string;
};

export type GlobalShortcutState = 'Pressed' | 'Released';

export type GlobalShortcutTriggered = {
	commandId: string;
	state: GlobalShortcutState;
};

/**
 *  The recording a window holds: the id it will publish under, the microphone
 *  it opened, and whether its capture has already ended.
 *
 *  One shape for both `start` and `current`, so a recording recovered after a
 *  reload is not a different kind of thing from one just started. `ended_reason`
 *  is the one fact a fresh start can never carry and a recovered one might.
 */
export type HostRecording = {
	audioBlobId: string;
	device: DeviceAcquisition;
	/**
	 *  `None` while capture is running. `Some` means capture is over and this
	 *  recording is waiting to be stopped (publishing what it captured) or
	 *  cancelled (discarding it).
	 */
	endedReason: EndedReason | null;
};

/**
 *  What an application may learn about the local transcription route: whether it
 *  is ready, and which advisory inputs it accepts.
 *
 *  Readiness and capability, never identity (ADR-0180). This is advisory UI
 *  state, not a preflight gate: a caller uses it to warn before capture and to
 *  decide whether to offer a prompt or language field, never to decide whether
 *  `transcribe_recording` may be called. Transcription resolves the active model
 *  independently at the point of use, so a stale read here can only produce a
 *  stale hint, never a wrong transcription.
 *
 *  That distinction is load-bearing because the shared Hugging Face cache can
 *  change outside Epicenter: a model deleted by another tool between this read
 *  and the next transcribe turns a `ready` answer stale, and the transcribe path
 *  still fails closed on its own.
 */
export type LocalTranscriptionReadiness =
	| {
			status: 'ready';
			/**  Whether the active model accepts an initial prompt. */
			supportsPrompt: boolean;
			/**  Whether it takes a spoken-language hint. */
			supportsLanguage: boolean;
	  }
	| {
			status: 'unavailable';
			reason: UnavailableReason;
			/**  A user-facing sentence that names no model. */
			message: string;
	  };

/**
 *  The OS-level microphone authorization, read from the platform privacy store.
 *
 *  Only `Granted` and `Unknown` are usable. `Unknown` (no entry in the store, or
 *  a platform with no such gate) means "can't tell from here": the caller treats
 *  it as available and lets the recorder's stream-open fallback
 *  (`recorder::error::classify_cpal`) classify any real denial from the error
 *  itself. So this signal can only *add* a pre-record denial; it never newly
 *  blocks a setup that was already working.
 *
 *  `NotDetermined` is the one state that is neither usable nor final: the user
 *  has not been asked yet. It is not `Unknown` (we know exactly what the OS
 *  thinks) and not `Denied` (nothing has been refused). It exists so
 *  `request_microphone_permission` can tell the one state that can still raise a
 *  system prompt from the states where prompting is a silent no-op.
 */
export type MicrophonePermission =
	| 'granted'
	| 'denied'
	| 'not_determined'
	| 'unknown';

/**
 *  A catalog model as Home's administration view sees it: identity, display
 *  fields, static capabilities, and whether it is already downloaded. Home names
 *  `id` when it activates, downloads, or deletes a model; it never learns the
 *  Hugging Face coordinate. Applications see none of this.
 */
export type ModelInfo = {
	id: string;
	name: string;
	description: string;
	/**
	 *  Approximate download size in bytes. `f64` because specta forbids 64-bit
	 *  ints in TS; model sizes are far below `f64`'s exact-integer ceiling.
	 */
	sizeBytes: number | null;
	supportsPrompt: boolean;
	supportsLanguage: boolean;
	recommended: boolean;
	downloaded: boolean;
};

export type RecorderError =
	/**
	 *  The OS refused microphone access. The frontend checks microphone
	 *  permission before recording, so this is the stream-open fallback for a
	 *  denial that slips past that gate (e.g. a declined first-run prompt).
	 */
	| { name: 'PermissionDenied'; message: string }
	/**
	 *  No usable input device: none selected and no default, the named device
	 *  is gone, cpal reports the device unavailable mid-open, or the device
	 *  yields no input configurations at all (query errors or returns empty).
	 */
	| { name: 'NoInputDevice'; message: string }
	/**
	 *  A recording started by some window is already in flight. There is one
	 *  host recorder, and a competing start is refused rather than silently
	 *  displacing a recording another window is relying on.
	 */
	| { name: 'Busy'; message: string }
	/**
	 *  The named recording is not this window's to end: it has already
	 *  finished, it is not the one in flight, or another window owns it. One
	 *  variant for all three because a caller cannot act differently on them,
	 *  and the distinguishing detail travels in `message`.
	 */
	| { name: 'NotRecording'; message: string }
	/**
	 *  Any other recording failure (device config, stream build, filesystem,
	 *  internal). The frontend does not branch on these.
	 */
	| { name: 'Failed'; message: string };

/**
 *  Pushed to the window that owns a recording when the host ends its capture
 *  without being asked. Carries the blob id so a window that has since started
 *  another recording can tell which one lost its microphone, and the reason so
 *  it can say something true about what happened.
 *
 *  A signal, never a result. It carries no audio and no blob: the recording is
 *  still the owner's, and `stop` publishes what it captured. Missing this event
 *  costs nothing, because `current_recording` reports the same ended recording.
 *  See `commands::end_recording_capture` for why.
 */
export type RecordingEndedEvent = {
	audioBlobId: string;
	reason: EndedReason;
};

/**
 *  Failures the Home administration commands can report. Both are actionable:
 *  the id is not a model this build knows, or the choice could not be made
 *  durable.
 */
export type SettingsError =
	| { name: 'UnknownModel'; message: string }
	| { name: 'SaveFailed'; message: string };

/**
 *  What `stop_recording` hands back: the committed blob's id and the two facts
 *  only the host can state exactly.
 *
 *  Both are computed here rather than in JS, where they used to be a wall-clock
 *  subtraction and a follow-up `stat` round trip. Wall clock measures how long
 *  the user held the button, which is not the same as how much audio the blob
 *  contains, and it had no answer at all after a reload.
 *
 *  Both are `u32` because the blob is a RIFF WAV and RIFF states its own sizes
 *  in 32 bits: the staged writer already refuses anything larger. So `u32` is
 *  the format's real bound rather than a convenient cap, and it renders in
 *  TypeScript as a plain `number` (specta widens `f64` to `number | null` to
 *  leave room for NaN, a value neither of these can hold).
 */
export type StoppedRecording = {
	audioBlobId: string;
	/**
	 *  Exact duration of the committed audio: the file's own sample count over
	 *  the rate it was captured at. This is the blob's length rather than how
	 *  long the button was held, so a sub-second clip padded at finalize reports
	 *  the padded duration, which is what the file actually holds.
	 */
	durationMs: number;
	/**  Exact length of the published file on disk. */
	byteLength: number;
};

export type TranscriptionError =
	| { name: 'AudioReadError'; message: string }
	/**
	 *  The local route cannot run at all: no model is active on this device, or
	 *  the active model's file is not here.
	 *
	 *  One public precondition family (ADR-0180). The two cases differ only as
	 *  compact `reason` data, because the caller's job is the same either way:
	 *  say so honestly and point at Home. `message` never names a model, since
	 *  model identity is administration data an application does not receive.
	 *
	 *  Failing here changes nothing. No model is adopted, downloaded,
	 *  substituted, or routed to the cloud on the caller's behalf.
	 */
	| {
			name: 'LocalRouteUnavailable';
			reason: UnavailableReason;
			message: string;
	  }
	/**
	 *  Operational, not a precondition: the active model was resolvable but the
	 *  runtime could not load it. Kept distinct so a broken install does not
	 *  read as "you have not set this up".
	 */
	| { name: 'ModelLoadError'; message: string }
	/**  Operational: inference itself failed. */
	| { name: 'TranscriptionError'; message: string };

/**
 *  The advisory hints an application supplies with a transcription.
 *
 *  Model identity is deliberately absent (ADR-0180): the host resolves the one
 *  active model at use, so an ordinary request cannot reassign the shared model
 *  cache. Language and prompt stay application-owned and read-at-use, exactly as
 *  ADR-0012 left them; nothing here is retained between calls.
 */
export type TranscriptionHints = {
	language?: string | null;
	initialPrompt?: string | null;
};

/**
 *  What a transcription request produced.
 *
 *  Two outcomes because there are two honest stories. `transcribed` names the
 *  exact model that produced the text, which is what makes an accidental
 *  substitution detectable: with the active model unchanged, identical ordinary
 *  requests must name the same model however the host arranges residency.
 *  `empty-audio` reports that nothing ran, and deliberately carries no model and
 *  no applied hints, because claiming either would be claiming an inference that
 *  never happened.
 */
export type TranscriptionOutcome =
	| {
			outcome: 'transcribed';
			text: string;
			modelId: string;
			applied: AppliedHints;
	  }
	/**  The audio held no samples, so no model was loaded and no hint applied. */
	| { outcome: 'empty-audio' };

/**
 *  Why the local transcription route cannot run right now.
 *
 *  A compact reason, deliberately not a model. It is enough for an application
 *  to write an honest sentence and name Home as the fix, and it carries no
 *  identity, no inventory, and nothing about what is cached or resident.
 */
export type UnavailableReason =
	/**  Nobody has chosen an active local model on this device. */
	| 'no-active-model'
	/**
	 *  A model is active, but it cannot run here: its file is not on this
	 *  machine, or it is not a model this build knows about.
	 */
	| 'active-model-unavailable';

/**
 *  How long after the last transcription the resident model should be dropped.
 *
 *  `Immediately` is enforced synchronously at the end of each transcription;
 *  timed variants are enforced by the background idle watcher.
 */
export type UnloadPolicy =
	| 'never'
	| 'immediately'
	| 'after_5_minutes'
	| 'after_30_minutes';

/**  Where `write_text` left the transcript. */
export type WriteTextOutcome =
	/**  The synthetic paste landed at the cursor. */
	| 'pasted'
	/**  Delivery could not paste, so the transcript remains on the clipboard. */
	| 'leftOnClipboard';

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}

type EventEmit<T> = [T] extends [null]
	? () => Promise<void>
	: (payload: T) => Promise<void>;

function makeEvent<T>(
	name: string,
	serialize?: (payload: T) => unknown,
	deserialize?: (payload: any) => T,
) {
	const mapEvent =
		(cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
			cb({
				...event,
				payload: deserialize ? deserialize(event.payload) : event.payload,
			});
	const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

	const base = {
		listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
			__TAURI_EVENT.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) =>
			__TAURI_EVENT.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			__TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	};

	const fn = (
		target:
			| import('@tauri-apps/api/webview').Webview
			| import('@tauri-apps/api/window').Window,
	) => ({
		listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
			target.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) =>
			target.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	});

	return Object.assign(fn, base);
}
